---
name: Crabflow Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            arch: x86_64
            name: Darwin_x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            arch: arm64
            name: Darwin_arm64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            arch: x86_64
            name: Linux_x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libssl-dev (Linux x86_64)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Set up Rust
        run: |
          rustup install stable
          rustup target add ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          tar -czvf crabflow_${{ matrix.name }}.tar.gz -C ./target/${{ matrix.target }}/release crabflow

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crabflow_${{ matrix.name }}.tar.gz
          path: crabflow_${{ matrix.name }}.tar.gz

  checksum:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERSIONTAG: ${{ github.event.release.tag_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Generate checksums
        run: |
          for file in artifacts/*.tar.gz/*.tar.gz; do
            sha256sum "$file" | awk '{gsub(/.*\//, "", $2); print $1 "  " $2}' >> crabflow_${{ env.VERSIONTAG }}_checksums.txt
          done

      - name: Upload checksum file
        uses: actions/upload-artifact@v4
        with:
          name: crabflow_${{ env.VERSIONTAG }}_checksums.txt
          path: crabflow_${{ env.VERSIONTAG }}_checksums.txt


  upload-release-assets:
    needs: [build, checksum]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./artifacts/crabflow_${{ github.event.release.tag_name }}_checksums.txt/crabflow_${{ github.event.release.tag_name }}_checksums.txt
            ./artifacts/crabflow_Darwin_x86_64.tar.gz/crabflow_Darwin_x86_64.tar.gz
            ./artifacts/crabflow_Darwin_arm64.tar.gz/crabflow_Darwin_arm64.tar.gz
            ./artifacts/crabflow_Linux_x86_64.tar.gz/crabflow_Linux_x86_64.tar.gz
